apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service
  labels:
    app: employee
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      labels:
        app: employee
    spec:
      volumes:
      - name: jks-certs-volume
        secret:
          secretName: kafka-jks-secret
      containers:
      - name: employee-app
        image: my-employee-service:v1
        imagePullPolicy: Never
        resources:
          requests:
            memory: "512Mi"   # అప్లికేషన్ స్టార్ట్ అవ్వడానికి కావాల్సిన కనీస మెమరీ
            cpu: "500m"       # 0.5 Core CPU
          limits:
            memory: "512Mi"   # అప్లికేషన్ గరిష్టంగా ఇంతకంటే ఎక్కువ వాడకూడదు
            cpu: "1000m"      # 1 Full Core CPU
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30 # అప్లికేషన్ స్టార్ట్ అవ్వడానికి ఇచ్చే సమయం
          periodSeconds: 10       # ప్రతి 10 సెకన్లకు చెక్ చేస్తుంది
        
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 5
        env:
        - name: APP_WELCOME_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: employee-config
              key: app.welcome.message
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: employee-db-secret
              key: db.password
        - name: TZ
          value: "Asia/Kolkata"
        volumeMounts:
        - name: jks-certs-volume
          mountPath: "/etc/certs"
          readOnly: true

---
apiVersion: v1
kind: Service
metadata:
  name: employee-svc
spec:
  type: NodePort
  selector:
    app: employee
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080